name: Run packer build on a template file

on:
  push:
    branches:
        - 'master'
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # validate templates
      - name: Validate Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: hpc-fvcom/packer-hpc-fvcom.json

      # build artifact
      - name: Build Artifact
        uses: operatehappy/packer-github-action
        with:
          command: build
          arguments: "-on-error=abort"
          target: hpc-fvcom/packer-hpc-fvcom.json

      # additional steps to process artifacts
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET : ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_ENVIRONMENT : public
          SAS_FVCOM_CODE : ${{ secrets.SAS_FVCOM_CODE }}
