name: Run packer build on a template file

on:
  push:
    branches:
        - 'master'
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Packer build
        uses: santisaez/packer-action@v1
        with:
          template: nginx-digitalocean.json
        env:
          DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          ARM_SUBSCRIPTION_ID: 
          ARM_CLIENT_ID: 
          ARM_CLIENT_SECRET : 
          ARM_TENANT_ID: 
          ARM_ENVIRONMENT : public
          